export type ItineraryVariant = {
  id: string;
  packageSlug?: string;
  region: string;
  title: string;
  duration: string;
  sourceGroup: string;
  publicHighlights: string[];
  days: string[];
};

export const itineraryCatalog: ItineraryVariant[] = [
  { id: "cusco-express", region: "Cusco", title: "Cusco esencial", duration: "3 días / 2 noches", sourceGroup: "Tours Cusco privados", publicHighlights: ["Valle Sagrado", "Machu Picchu", "City tour de Cusco"], days: ["Llegada a Cusco, recepción, aclimatación y orientación del viaje.", "Valle Sagrado: Pisac, Urubamba y Ollantaytambo según horario confirmado.", "Machu Picchu con tren, bus, ingreso programado y retorno asistido; el city tour se ajusta al vuelo."] },
  { id: "cusco-imperial", region: "Cusco", title: "Cusco Imperial", duration: "5 días / 4 noches", sourceGroup: "Tours Cusco", publicHighlights: ["Sacsayhuamán", "Valle Sagrado", "Machu Picchu", "Maras, Moray y Salineras"], days: ["Llegada, traslado, aclimatación y recorrido por Sacsayhuamán, Cristo Blanco, Qenqo, Tambomachay y Puca Pucara.", "Valle Sagrado con Pisac, almuerzo en Urubamba, Ollantaytambo y Chinchero.", "Salida a Ollantaytambo, tren a Aguas Calientes, bus e ingreso guiado a Machu Picchu; retorno asistido.", "Maras, terrazas de Moray y Salineras; actividades adicionales sujetas a la propuesta.", "Desayuno, tiempo libre y traslado coordinado al aeropuerto."] },
  { id: "cusco-aventura", region: "Cusco", title: "Cusco aventura y naturaleza", duration: "7 días / 6 noches", sourceGroup: "Tours Cusco", publicHighlights: ["Machu Picchu", "Montaña de Siete Colores", "Laguna Humantay", "Valle Sur"], days: ["Llegada a Cusco, recepción y circuito arqueológico cercano.", "Valle Sagrado de los Incas.", "Traslado a Aguas Calientes y preparación del ingreso.", "Visita guiada a Machu Picchu.", "Excursión a la Montaña de Siete Colores, sujeta a condición física y clima.", "Excursión a Laguna Humantay, sujeta a condición física y clima.", "Valle Sur y retorno coordinado."] },
  { id: "andes-sur", packageSlug: "machu-picchu", region: "Sur del Perú", title: "Cusco, Puno y Arequipa", duration: "7 días / 6 noches", sourceGroup: "Tours Cusco, Puno y Arequipa 2026", publicHighlights: ["Cusco y Machu Picchu", "Lago Titicaca", "Arequipa", "Ruta altiplánica"], days: ["Llegada a Cusco, aclimatación y circuito arqueológico de Sacsayhuamán.", "Valle Sagrado con Pisac, Urubamba, Ollantaytambo y Chinchero.", "Machu Picchu con tren, bus, ingreso programado y guiado.", "Valle Sur y salida nocturna hacia Puno.", "Navegación por el lago Titicaca, islas de los Uros y circuito cultural en Chucuito.", "Chullpas de Sillustani y traslado nocturno hacia Arequipa.", "Mirador de Yanahuara, centro histórico y retorno coordinado desde Arequipa."] },
  { id: "cusco-ica-lima", packageSlug: "cusco-ica-lima-2027", region: "Perú", title: "Cusco, Ica y Lima", duration: "9 días / 8 noches", sourceGroup: "Tours Cusco privados 2027", publicHighlights: ["Cusco y Valle Sagrado", "Machu Picchu", "Montaña de Siete Colores", "Paracas y Huacachina"], days: ["Llegada a Lima y conexión aérea hacia Cusco.", "City tour de Cusco y circuito arqueológico cercano.", "Valle Sagrado con Pisac, Urubamba y Ollantaytambo.", "Machu Picchu con tren, bus, ingreso programado y guiado.", "Valle Sur o Maras, Moray y Salineras según la propuesta confirmada.", "Montaña de Siete Colores y retorno aéreo a Lima.", "Centro histórico de Lima.", "Full day Islas Ballestas, Paracas, Ica y Huacachina.", "Traslado de salida según el vuelo internacional contratado."] },
  { id: "tarapoto-clasico", packageSlug: "tarapoto-naturaleza", region: "Amazonía", title: "Tarapoto clásico", duration: "5 días / 4 noches", sourceGroup: "Tours Tarapoto", publicHighlights: ["Lamas", "Laguna Azul", "Rioja y Moyobamba", "Cataratas"], days: ["Llegada a Tarapoto y recorrido cultural por Lamas.", "Excursión a la Laguna Azul del Sauce.", "Full day en Rioja y Moyobamba.", "Catarata de Ahuashiyacu.", "Huacamaillo o Pishurayacu, según condiciones, y retorno."] },
  { id: "tarapoto-chachapoyas", packageSlug: "tarapoto-naturaleza", region: "Amazonía", title: "Tarapoto y Chachapoyas", duration: "6 días / 5 noches", sourceGroup: "Tours Tarapoto", publicHighlights: ["Laguna Azul", "Moyobamba", "Kuélap", "Sarcófagos de Karajía"], days: ["Llegada a Tarapoto y traslado al alojamiento.", "Laguna Azul del Sauce.", "Rioja, Moyobamba y traslado hacia Chachapoyas.", "Visita a la ciudad fortificada de Kuélap, sujeta a accesos vigentes.", "Ruta cultural a los Sarcófagos de Karajía.", "Retorno coordinado según vuelo o transporte contratado."] },
  { id: "norte-peru", packageSlug: "mancora-punta-sal-tumbes", region: "Norte del Perú", title: "Máncora, Punta Sal y Tumbes", duration: "5 días / 4 noches", sourceGroup: "Tours Norte", publicHighlights: ["Máncora", "Punta Sal", "Tortugas de Ñuro", "Manglares de Tumbes"], days: ["Llegada a Piura o Tumbes y traslado al alojamiento.", "Día de playa entre Máncora y Punta Sal.", "Experiencia marina en Ñuro, sujeta a condiciones del operador.", "Manglares y Puerto Pizarro.", "Retorno coordinado por Piura o Tumbes."] },
  { id: "guayaquil", packageSlug: "guayaquil-costa-ecuador", region: "Ecuador", title: "Guayaquil ejecutivo", duration: "3 días / 2 noches", sourceGroup: "Tours Norte Perú Ecuador 2025", publicHighlights: ["Cerro Santa Ana", "Las Peñas", "Malecón 2000", "Río Guayas"], days: ["Traslado desde la frontera, llegada a Guayaquil, cena e instalación.", "Full day por Cerro Santa Ana, Las Peñas, teleférico, río Guayas, Parque de las Iguanas y Malecón 2000.", "Desayuno y retorno coordinado por la frontera Ecuador–Perú."] },
  { id: "cartagena", packageSlug: "cartagena-islas-caribe", region: "Colombia", title: "Cartagena e islas", duration: "5 días / 4 noches", sourceGroup: "Tours Colombia", publicHighlights: ["Cartagena", "Santa Marta", "Islas del Rosario", "Barú"], days: ["Llegada a Cartagena y recorrido panorámico.", "Full day Cartagena y Santa Marta según programa.", "Excursión a Islas del Rosario.", "Día de playa en Barú.", "City tour histórico y retorno a Lima."] },
  { id: "rio", packageSlug: "rio-de-janeiro", region: "Brasil", title: "Río de Janeiro ejecutivo", duration: "6 días / 5 noches", sourceGroup: "Tours Brasil 2026", publicHighlights: ["Cristo Redentor", "Pan de Azúcar", "Petrópolis", "Centro histórico"], days: ["Salida de Lima hacia Brasil.", "Llegada y recorrido por el centro histórico, Catedral, Escalera de Selarón, Lapa y exteriores del Maracaná.", "Cristo Redentor, Pan de Azúcar y circuito panorámico por Tijuca.", "Full day en Petrópolis con Museo Imperial y centro histórico.", "Día libre con asistencia para actividades opcionales.", "Traslado al aeropuerto y retorno a Lima."] },
  { id: "iguazu", packageSlug: "buenos-aires-iguazu", region: "Argentina y Brasil", title: "Buenos Aires e Iguazú", duration: "10 días / 9 noches", sourceGroup: "Tours Argentina Iguazú 2026", publicHighlights: ["Buenos Aires", "Tigre y Delta", "Cataratas de Iguazú", "Ruta Argentina–Brasil"], days: ["Salida de Lima y llegada a Buenos Aires.", "City tour de Buenos Aires y navegación por Tigre–Delta.", "Día libre asistido en Buenos Aires.", "Día libre para una experiencia opcional coordinada.", "Jornada cultural o de compras según la propuesta final.", "Vuelo a Puerto Iguazú y experiencia al atardecer en Tres Fronteras.", "Cataratas del lado argentino.", "Cataratas del lado brasileño y recorrido urbano sujeto a documentación migratoria.", "Retorno a Buenos Aires.", "Traslado al aeropuerto y regreso a Lima."] },
  { id: "punta-cana", packageSlug: "punta-cana-santo-domingo", region: "Caribe", title: "Punta Cana y Santo Domingo", duration: "6 días / 5 noches", sourceGroup: "Tours Punta Cana 2026", publicHighlights: ["Isla Saona", "Isla Catalina", "Santo Domingo", "Buggies"], days: ["Salida de Lima, llegada a Punta Cana y traslado al alojamiento.", "Excursión en barco a Isla Saona.", "Excursión a Isla Catalina.", "City tour por la zona colonial de Santo Domingo.", "Experiencia de buggies, Playa Macao y Cueva del Salado, sujeta a condiciones.", "Cierre del programa y retorno coordinado a Lima."] },
  { id: "disney", packageSlug: "disney-orlando", region: "Estados Unidos", title: "Disney y Orlando", duration: "7 días / 6 noches", sourceGroup: "Tours Disney 2026", publicHighlights: ["Orlando", "Magic Kingdom", "Epcot", "Universal Studios"], days: ["Vuelo internacional y conexión hacia Estados Unidos.", "Llegada a Orlando, recepción y traslado al alojamiento.", "Magic Kingdom según entradas confirmadas.", "Epcot según entradas confirmadas.", "Universal Studios según entradas confirmadas.", "Mañana libre para compras y conexión de retorno.", "Vuelo de regreso y llegada a Lima."] },
  { id: "punta-sal-cultural", packageSlug: "punta-sal-norte-cultural", region: "Norte del Perú", title: "Punta Sal y norte cultural", duration: "6 días / 5 noches", sourceGroup: "Tours Norte con resort 2025", publicHighlights: ["Punta Sal", "Puerto Pizarro", "Máncora y Ñuro", "Chiclayo y Sipán"], days: ["Vuelo a Tumbes y llegada a Punta Sal.", "Día de playa y actividades incluidas en el alojamiento confirmado.", "Puerto Pizarro, manglares y traslado hacia la zona de Acapulco.", "Máncora y experiencia marina en Ñuro, sujeta a condiciones del operador.", "Piura, Catacaos y traslado hacia Chiclayo.", "Museo Tumbas Reales, Huaca Rajada, Túcume y retorno a Lima."] },
  { id: "europa-clasica", packageSlug: "europa-esencial-madrid-paris-roma", region: "Europa", title: "Europa Clásica", duration: "15 días / 14 noches", sourceGroup: "Tours Europa", publicHighlights: ["Madrid y Barcelona", "Roma, Florencia y Venecia", "París", "Costa Azul"], days: ["Lima–Madrid.", "Madrid y recorrido panorámico.", "Madrid–Zaragoza–Barcelona.", "Barcelona–Costa Azul.", "Costa Azul–Pisa–Roma.", "Roma monumental.", "Roma–Florencia.", "Florencia–Venecia.", "Venecia–Annemasse.", "Annemasse–París.", "París panorámico.", "París–Lourdes.", "Lourdes–San Sebastián–Madrid.", "Madrid y actividades confirmadas.", "Retorno según vuelos contratados."] },
  { id: "suenos-europa", packageSlug: "europa-esencial-madrid-paris-roma", region: "Europa", title: "Sueños de Europa", duration: "17 días / 15 noches", sourceGroup: "Tours Europa", publicHighlights: ["Madrid", "París", "Zúrich", "Italia", "Barcelona"], days: ["Lima–Madrid.", "Madrid y recepción.", "Madrid panorámico.", "Madrid–Burgos–Burdeos.", "Burdeos–Blois–París.", "París.", "París y actividades opcionales.", "París–Zúrich.", "Zúrich–Milán–Véneto.", "Venecia–Florencia.", "Florencia–Roma.", "Roma.", "Roma y Vaticano según entradas.", "Roma–Pisa–Costa Azul.", "Costa Azul–Barcelona.", "Barcelona–Zaragoza–Madrid.", "Madrid–Lima."] }
];

export const itineraryVariantsFor = (slug: string) => itineraryCatalog.filter((item) => item.packageSlug === slug);
