export type ItineraryVariant = {
  id: string;
  packageSlug?: string;
  region: string;
  title: string;
  duration: string;
  sourceGroup: string;
  publicHighlights: string[];
  days: string[];
};

export const itineraryCatalog: ItineraryVariant[] = [
  { id: "cusco-express", packageSlug: "machu-picchu", region: "Cusco", title: "Cusco esencial", duration: "3 días / 2 noches", sourceGroup: "Tours Cusco privados", publicHighlights: ["Valle Sagrado", "Machu Picchu", "City tour de Cusco"], days: ["Llegada a Cusco, recepción, aclimatación y orientación del viaje.", "Valle Sagrado: Pisac, Urubamba y Ollantaytambo según horario confirmado.", "Machu Picchu con tren, bus, ingreso programado y retorno asistido; el city tour se ajusta al vuelo."] },
  { id: "cusco-imperial", packageSlug: "machu-picchu", region: "Cusco", title: "Cusco Imperial", duration: "5 días / 4 noches", sourceGroup: "Tours Cusco", publicHighlights: ["Sacsayhuamán", "Valle Sagrado", "Machu Picchu", "Maras, Moray y Salineras"], days: ["Llegada, traslado, aclimatación y recorrido por Sacsayhuamán, Cristo Blanco, Qenqo, Tambomachay y Puca Pucara.", "Valle Sagrado con Pisac, almuerzo en Urubamba, Ollantaytambo y Chinchero.", "Salida a Ollantaytambo, tren a Aguas Calientes, bus e ingreso guiado a Machu Picchu; retorno asistido.", "Maras, terrazas de Moray y Salineras; actividades adicionales sujetas a la propuesta.", "Desayuno, tiempo libre y traslado coordinado al aeropuerto."] },
  { id: "cusco-aventura", packageSlug: "machu-picchu", region: "Cusco", title: "Cusco aventura y naturaleza", duration: "7 días / 6 noches", sourceGroup: "Tours Cusco", publicHighlights: ["Machu Picchu", "Montaña de Siete Colores", "Laguna Humantay", "Valle Sur"], days: ["Llegada a Cusco, recepción y circuito arqueológico cercano.", "Valle Sagrado de los Incas.", "Traslado a Aguas Calientes y preparación del ingreso.", "Visita guiada a Machu Picchu.", "Excursión a la Montaña de Siete Colores, sujeta a condición física y clima.", "Excursión a Laguna Humantay, sujeta a condición física y clima.", "Valle Sur y retorno coordinado."] },
  { id: "andes-sur", packageSlug: "lago-titicaca-ruta-bolivia", region: "Andes del sur", title: "Cusco, Puno y Arequipa", duration: "8 días / 7 noches", sourceGroup: "Tours Cusco", publicHighlights: ["Cusco y Machu Picchu", "Lago Titicaca", "Arequipa", "Ruta altiplánica"], days: ["Llegada a Cusco y aclimatación.", "Valle Sagrado de los Incas.", "Machu Picchu con ingreso programado.", "Ruta terrestre hacia Puno con paradas culturales confirmadas.", "Navegación por el lago Titicaca.", "Traslado hacia Arequipa.", "City tour y espacios históricos de Arequipa.", "Retorno según el transporte contratado."] },
  { id: "tarapoto-clasico", packageSlug: "tarapoto-naturaleza", region: "Amazonía", title: "Tarapoto clásico", duration: "5 días / 4 noches", sourceGroup: "Tours Tarapoto", publicHighlights: ["Lamas", "Laguna Azul", "Rioja y Moyobamba", "Cataratas"], days: ["Llegada a Tarapoto y recorrido cultural por Lamas.", "Excursión a la Laguna Azul del Sauce.", "Full day en Rioja y Moyobamba.", "Catarata de Ahuashiyacu.", "Huacamaillo o Pishurayacu, según condiciones, y retorno."] },
  { id: "tarapoto-chachapoyas", packageSlug: "tarapoto-naturaleza", region: "Amazonía", title: "Tarapoto y Chachapoyas", duration: "6 días / 5 noches", sourceGroup: "Tours Tarapoto", publicHighlights: ["Laguna Azul", "Moyobamba", "Kuélap", "Sarcófagos de Karajía"], days: ["Llegada a Tarapoto y traslado al alojamiento.", "Laguna Azul del Sauce.", "Rioja, Moyobamba y traslado hacia Chachapoyas.", "Visita a la ciudad fortificada de Kuélap, sujeta a accesos vigentes.", "Ruta cultural a los Sarcófagos de Karajía.", "Retorno coordinado según vuelo o transporte contratado."] },
  { id: "norte-peru", packageSlug: "mancora-punta-sal-tumbes", region: "Norte del Perú", title: "Máncora, Punta Sal y Tumbes", duration: "5 días / 4 noches", sourceGroup: "Tours Norte", publicHighlights: ["Máncora", "Punta Sal", "Tortugas de Ñuro", "Manglares de Tumbes"], days: ["Llegada a Piura o Tumbes y traslado al alojamiento.", "Día de playa entre Máncora y Punta Sal.", "Experiencia marina en Ñuro, sujeta a condiciones del operador.", "Manglares y Puerto Pizarro.", "Retorno coordinado por Piura o Tumbes."] },
  { id: "guayaquil", packageSlug: "guayaquil-costa-ecuador", region: "Ecuador", title: "Guayaquil y costa ecuatoriana", duration: "3 días / 2 noches", sourceGroup: "Tours Norte Perú Ecuador", publicHighlights: ["Guayaquil", "Malecón", "La Perla", "Experiencia costera"], days: ["Traslado fronterizo o aéreo y llegada a Guayaquil.", "Full day urbano por los espacios confirmados de Guayaquil.", "Experiencia costera o tiempo libre y retorno coordinado."] },
  { id: "cartagena", packageSlug: "cartagena-islas-caribe", region: "Colombia", title: "Cartagena e islas", duration: "5 días / 4 noches", sourceGroup: "Tours Colombia", publicHighlights: ["Cartagena", "Santa Marta", "Islas del Rosario", "Barú"], days: ["Llegada a Cartagena y recorrido panorámico.", "Full day Cartagena y Santa Marta según programa.", "Excursión a Islas del Rosario.", "Día de playa en Barú.", "City tour histórico y retorno a Lima."] },
  { id: "rio", packageSlug: "rio-de-janeiro", region: "Brasil", title: "Río de Janeiro", duration: "6 días / 5 noches", sourceGroup: "Tours Brasil", publicHighlights: ["Río de Janeiro", "Pan de Azúcar", "Petrópolis", "Día libre asistido"], days: ["Salida desde Lima hacia Brasil.", "Llegada a Río de Janeiro, recepción y traslado.", "Visita al Pan de Azúcar y puntos panorámicos confirmados.", "Recorrido histórico por Petrópolis.", "Día libre con actividades opcionales coordinadas.", "Traslado al aeropuerto y retorno a Lima."] },
  { id: "iguazu", packageSlug: "buenos-aires-iguazu", region: "Argentina", title: "Buenos Aires e Iguazú", duration: "8 días / 7 noches", sourceGroup: "Tours Argentina Iguazú", publicHighlights: ["Buenos Aires", "Tigre y Delta", "Cataratas de Iguazú", "Ruta Argentina–Brasil"], days: ["Vuelo a Buenos Aires y recepción.", "City tour y circuito Tigre–Delta.", "Día cultural o experiencia opcional en Buenos Aires.", "Traslado aéreo o terrestre hacia Iguazú.", "Cataratas del lado argentino.", "Cataratas del lado brasileño, sujeto a documentación migratoria.", "Tiempo libre o actividad opcional coordinada.", "Retorno a Lima según vuelos confirmados."] },
  { id: "punta-cana", packageSlug: "punta-cana-santo-domingo", region: "Caribe", title: "Punta Cana y Santo Domingo", duration: "5 días / 4 noches", sourceGroup: "Tours Punta Cana", publicHighlights: ["Isla Saona", "Isla Catalina", "Santo Domingo", "Buggies"], days: ["Salida de Lima, llegada a Punta Cana y traslado.", "Excursión a Isla Saona.", "Excursión a Isla Catalina.", "City tour histórico en Santo Domingo.", "Experiencia de buggies, según condiciones, y retorno a Lima."] },
  { id: "disney", packageSlug: "disney-orlando", region: "Estados Unidos", title: "Disney y Orlando", duration: "8 días / 7 noches", sourceGroup: "Tours Disney", publicHighlights: ["Miami", "Magic Kingdom", "Epcot", "Universal Studios"], days: ["Vuelo internacional y llegada a Miami.", "Recorrido de bienvenida y traslado hacia Orlando.", "Magic Kingdom según entradas confirmadas.", "Epcot según entradas confirmadas.", "Universal Studios según entradas confirmadas.", "Día libre para compras o parque adicional.", "Traslado de salida y conexión aérea.", "Llegada a Lima."] },
  { id: "europa-clasica", packageSlug: "europa-esencial-madrid-paris-roma", region: "Europa", title: "Europa Clásica", duration: "15 días / 14 noches", sourceGroup: "Tours Europa", publicHighlights: ["Madrid y Barcelona", "Roma, Florencia y Venecia", "París", "Costa Azul"], days: ["Lima–Madrid.", "Madrid y recorrido panorámico.", "Madrid–Zaragoza–Barcelona.", "Barcelona–Costa Azul.", "Costa Azul–Pisa–Roma.", "Roma monumental.", "Roma–Florencia.", "Florencia–Venecia.", "Venecia–Annemasse.", "Annemasse–París.", "París panorámico.", "París–Lourdes.", "Lourdes–San Sebastián–Madrid.", "Madrid y actividades confirmadas.", "Retorno según vuelos contratados."] },
  { id: "suenos-europa", packageSlug: "europa-esencial-madrid-paris-roma", region: "Europa", title: "Sueños de Europa", duration: "17 días / 15 noches", sourceGroup: "Tours Europa", publicHighlights: ["Madrid", "París", "Zúrich", "Italia", "Barcelona"], days: ["Lima–Madrid.", "Madrid y recepción.", "Madrid panorámico.", "Madrid–Burgos–Burdeos.", "Burdeos–Blois–París.", "París.", "París y actividades opcionales.", "París–Zúrich.", "Zúrich–Milán–Véneto.", "Venecia–Florencia.", "Florencia–Roma.", "Roma.", "Roma y Vaticano según entradas.", "Roma–Pisa–Costa Azul.", "Costa Azul–Barcelona.", "Barcelona–Zaragoza–Madrid.", "Madrid–Lima."] }
];

export const itineraryVariantsFor = (slug: string) => itineraryCatalog.filter((item) => item.packageSlug === slug);
