export type TourMediaItem = {
  image: string;
  title: string;
  stage: string;
  alt: string;
};

export type TourMediaCollection = {
  introduction: string;
  items: TourMediaItem[];
};

/** Local previews are generated by scripts/generate-tour-previews.cjs. */
export const tourPhotoPreview = (image: string) => image.startsWith("/tour-galleries/") ? image.replace(/\.webp$/, "-preview.webp") : image;

export const tourMediaBySlug: Record<string, TourMediaCollection> = {
  "machu-picchu": {
    introduction: "Una sola propuesta conecta Cusco y Machu Picchu con el lago Titicaca en Puno y la etapa final en Arequipa.",
    items: [
      { image: "/tour-galleries/machu-picchu/cusco-centro.webp", title: "Centro histórico de Cusco", stage: "Inicio de la experiencia", alt: "Viajeros de JohnToursPerú en la Plaza de Armas de Cusco" },
      { image: "/tour-galleries/machu-picchu/machu-picchu.webp", title: "Machu Picchu", stage: "Visita principal", alt: "Grupo de viajeros frente a Machu Picchu" },
      { image: "/tour-galleries/bolivia/lago-titicaca.webp", title: "Lago Titicaca, Puno", stage: "Ruta altiplánica", alt: "Viajeros de JohnToursPerú junto al Lago Titicaca en Puno" },
      { image: "/tour-galleries/machu-picchu/valle-sagrado.webp", title: "Valle Sagrado", stage: "Circuito cultural", alt: "Equipo de JohnToursPerú durante un recorrido por el Valle Sagrado" },
      { image: "/tour-galleries/bolivia/uros.webp", title: "Islas de los Uros", stage: "Puno · Cultura viva", alt: "Viajeros sobre una isla de totora de los Uros en el lago Titicaca" },
      { image: "/tour-galleries/machu-picchu/arequipa.webp", title: "Mirador de Yanahuara", stage: "Arequipa · Ciudad Blanca", alt: "Vista de Arequipa y su paisaje volcánico desde un arco del mirador de Yanahuara" }
    ]
  },
  "lago-titicaca-ruta-bolivia": {
    introduction: "La propuesta combina paisajes del Titicaca y una conexión terrestre coordinada hacia Bolivia, sujeta a la documentación y condiciones vigentes.",
    items: [
      { image: "/tour-galleries/bolivia/lago-titicaca.webp", title: "Lago Titicaca", stage: "Paisaje y cultura", alt: "Viajeros de JohnToursPerú junto al Lago Titicaca" },
      { image: "/tour-galleries/bolivia/frontera-bolivia.webp", title: "Conexión con Bolivia", stage: "Tramo internacional", alt: "Grupo de viajeros en el ingreso terrestre a Bolivia" },
      { image: "/tour-galleries/bolivia/uros.webp", title: "Islas de los Uros", stage: "Puno · Lago Titicaca", alt: "Grupo de viajeros en una isla flotante de los Uros" },
      { image: "/tour-galleries/bolivia/sillustani.webp", title: "Chullpas de Sillustani", stage: "Puno · Consulta esta extensión", alt: "Viajeros frente a una torre funeraria de piedra en Sillustani" }
    ]
  },
  "guayaquil-costa-ecuador": {
    introduction: "Del Malecón y Las Peñas a la costa ecuatoriana. Consulta la extensión a Montañita para combinar ciudad, cultura y playa.",
    items: [
      { image: "/tour-galleries/guayaquil/malecon.webp", title: "Malecón de Guayaquil", stage: "Recorrido urbano", alt: "Grupo de viajeros en el Malecón de Guayaquil" },
      { image: "/tour-galleries/guayaquil/las-penas.webp", title: "Las Peñas", stage: "Barrio patrimonial", alt: "Viajeros en las escalinatas coloridas de Las Peñas" },
      { image: "/tour-galleries/guayaquil/la-perla.webp", title: "La Perla", stage: "Panorama nocturno", alt: "Rueda panorámica La Perla iluminada por la noche" },
      { image: "/tour-galleries/guayaquil/montanita.webp", title: "Montañita", stage: "Costa · Extensión por confirmar", alt: "Viajeros junto al mural de bienvenida de Montañita, Ecuador" }
    ]
  },
  "ica-y-huacachina": {
    introduction: "La experiencia se concentra en las dunas de Huacachina, el paseo en tubular y las actividades que se confirman con el asesor.",
    items: [
      { image: "/tour-galleries/ica/dunas.webp", title: "Dunas de Huacachina", stage: "Atardecer en el desierto", alt: "Grupo de viajeros en las dunas de Huacachina" },
      { image: "/tour-galleries/ica/tubulares.webp", title: "Aventura en tubular", stage: "Actividad principal", alt: "Equipo de JohnToursPerú junto a un vehículo tubular en Ica" }
    ]
  },
  "oxapampa-pozuzo": {
    introduction: "El paquete reúne identidad local, paisajes de selva alta y experiencias culturales que se ajustan a la fecha elegida.",
    items: [
      { image: "/tour-galleries/pozuzo/portico.webp", title: "Pórtico de Pozuzo", stage: "Bienvenida al destino", alt: "Equipo de JohnToursPerú en el pórtico tradicional de Pozuzo" },
      { image: "/tour-galleries/pozuzo/comunidad-local.webp", title: "Experiencia cultural en Pozuzo", stage: "Encuentro con la comunidad", alt: "Grupo de viajeros de JohnToursPerú durante una experiencia cultural en Pozuzo" },
      { image: "/tour-galleries/pozuzo/catarata.webp", title: "Catarata de Pozuzo", stage: "Naturaleza de selva alta", alt: "Grupo de viajeros junto a una catarata durante el tour de Pozuzo" }
    ]
  }
};
